// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package netapp

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "netapp", asset.ModuleFieldsPri, AssetNetapp); err != nil {
		panic(err)
	}
}

// AssetNetapp returns asset data.
// This is the base64 encoded zlib format compressed contents of module/netapp.
func AssetNetapp() string {
	return "eJx0j8HOgjAQhO99igl3/gfo4U+MZ32Hxg7YWNqGLom8vcGCKQbnOLP77WyLB2eNQDEpKUCceGo0xWgUYJlvo0viYtD4VwDWaVyinTwV0Dl6m/U7axHMwIq4SOZEjX6M0+YcUPecmmUm6+TjHuF+IovOMYhxIa8X0MURcieu5ZHTwoePff6r1r7b1I0G5mx67rKtl/Ap6hUAAP//M0NexQ=="
}
