// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package netapp

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "netapp", asset.ModuleFieldsPri, AssetNetapp); err != nil {
		panic(err)
	}
}

// AssetNetapp returns asset data.
// This is the base64 encoded zlib format compressed contents of module/netapp.
func AssetNetapp() string {
	return "eJycj7EOgjAQhvc+xR92HHTrYGKc9R0ae2BjaRvuSOTtDQKmGHDwxv/6ff2vxIN6jUBiUlKAOPGkUYxBoQBLfGtdEheDxlEBmF7jEm3nSQGVI29Zv3clgmkoMw4jfSKNuo3dnKxYl57cZTrr5JOu6TaV45xjEOMCTz+gii3kTriOh5wGP3yseZdh323yRg0xm5oWu7mX0FN+Qfu/qMM29QoAAP//TSd37g=="
}
