- module: linux
  period: 10s
  metricsets:
    - "pageinfo"
    - "memory"
    # - ksm
    # - conntrack
    # - iostat
    # - pressure
<<<<<<< HEAD
    # - rapl
=======
>>>>>>> e49f2579c ([Metricbeat] Add Linux pressure metricset (#27355))
  enabled: true
  #hostfs: /hostfs
  #rapl.use_msr_safe: false

