// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package oracle

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "oracle", asset.ModuleFieldsPri, AssetOracle); err != nil {
		panic(err)
	}
}

// AssetOracle returns asset data.
// This is the base64 encoded zlib format compressed contents of module/oracle.
func AssetOracle() string {
	return "eJx0j8FugzAQRO98xSj39AN8qNRLb1U/IUL24FoxLFpv1PL3FZBUppA9zs68nT3jyslBtPWZDWDJMh1Oq3BqgMDiNY2WZHB4bQDc3fiQcFtCXWIOxS27M4a2Z0Wcx6aRDlHlNt6VA+qWU7N6ltJG/ukPoPHHduY2U+2SJe7s9f2nHdZ5X5qgU+lhX8Tn+vHbzEaWiC5llpcq87/7ppKfb2xWj05XTt+i4TBGVdGLl8DDaBqMkdr8BgAA///RjXnB"
}
